[platformio]
src_dir = app
test_dir = test
; build_dir = ${sysenv.PIO_BUILD_DIR:-.pio}
; build_dir = ${sysenv.PIO_BUILD_DIR}

[env]
lib_deps = throwtheswitch/Unity@^2.5.2

[env:native]
platform = native
build_flags = 
    -I components/current_monitor/include
    -D UNITY_INT_WIDTH=32
    -lm

[env:esp32_base]
platform = espressif32
board = esp32dev
lib_extra_dirs = components
framework = espidf
monitor_speed = 115200
board_build.flash_size = 4MB

; [env:esp32_test]
; extends = env:esp32_base
; test_build_src = yes
; build_flags = 
;     -I components/current_monitor/include
;     -D UNITY_INT_WIDTH=16
; build_src_filter = 
;     +<components/*/src/*.c>
;     +<test/current_monitor/*.c>

[env:bare_metal]
extends = env:esp32_base
build_flags = -DCHOSEN_APP_BARE_METAL

[env:rtos]
extends = env:esp32_base
build_flags = -DCHOSEN_APP_RTOS
