[platformio]
# We set a common root for source, but we will filter it per environment
src_dir = app

[env]
platform = espressif32
board = esp32dev
framework = espidf
lib_extra_dirs = components
build_flags = 
#    -std=gnu++2b 
    -I components/current_monitor/include

[env:bare_metal]
build_src_filter = +<bare_metal/src/>
build_flags = 
    ${env.build_flags}
    -I app/bare_metal/include

[env:rtos]
build_src_filter = +<rtos/src/>
build_flags = 
    ${env.build_flags}
    -I app/rtos/include
