; [platformio]
; src_dir = app

[env]
platform = espressif32
board = esp32dev
framework = espidf
lib_extra_dirs = components
board_build.flash_size = 4MB
monitor_speed = 115200

[env:bare_metal]
src_dir = app/bare_metal/src/
; build_src_filter = +<bare_metal/src/>
build_flags = 
    -I app/bare_metal/include
    -I components/current_monitor/include

[env:rtos]
src_dir = app/rtos/src/
; build_src_filter = +<rtos/src/>
build_flags = 
    -I app/rtos/include
    -I components/current_monitor/include
